### PR TITLE
fix: beforeAll() executing before each test case

### LINKED ISSUE #90: beforeAll() executes after each test case
## Summary

Maybe I just don't understand the functionality of Rhum.beforeAll because I'm stupid, but it seems that the the function input into Rhum.beforeAll gets executed for every test case instead of just once before all testcases. If this really is how Rhum.beforeOnly, then I would like for this to be changed to having the function that is input into Rhum.beforeAll be executed once before all test cases, as this is the convention of most other Javascript/Typescript testing frameworks. [beforeAll vs beforeEach](https://stackoverflow.com/questions/54517032/beforeall-vs-beforeeach-when-to-use-them)

## Steps To Reproduce The Bug
Consider the following typescript file: 
```ts
// blah.ts
import { Rhum } from 'https://deno.land/x/rhum@v1.1.4/mod.ts';

Rhum.testPlan('foo', () => {
    Rhum.testSuite('bar', () => {
        let i = 0;
        Rhum.beforeAll(() => {
            console.log('In beforeAll, the value of i is ' + i);
            i++;
        });

        Rhum.testCase('inch', () => {
            Rhum.asserts.assertEquals(1, 1);
        });

        Rhum.testCase('time', () => {
            Rhum.asserts.assertEquals(1, 1);
        });

        Rhum.testCase('foot', () => {
            Rhum.asserts.assertEquals(1, 1);
        });

        Rhum.testCase('gem', () => {
            Rhum.asserts.assertEquals(1, 1);
        });
    });
});

Rhum.run();
```

If we run the command `deno test --allow-env blah.ts`, how many times does the function input into Rhum.beforeAll get executed?
blah

## Expected Behavior

I would like the function input into Rhum.beforeAll to be executed ONE time before all test cases, not once for every test case.

### PR DESCRIPTION
**Pull request by crookse**
Closes #90 

## Summary

* Adds flags to check when hooks are executed and only executes them when they're set to false
* Fixes assertions in tests (we were doing it wrong). If you read the before_all and before_each tests in master, you'll see that they're incorrectly asserting values. That's why we didn't catch the issue mentioned in this PR.

### CODE REVIEW

**Review by ebebbington — APPROVED** [review]

File: src/test_case.ts [hunk 1]
```diff
@@ -25,37 +25,64 @@ export class TestCase {
...
+    let executedBeforeAllSuiteHook = false;
+    let executedAfterAllSuiteHook = false;
+
     Object.keys(this.plan.suites).forEach((suiteName) => {
+      // Track the execution of hooks
+      let executedBeforeEachSuiteHook = false;
+      let executedAfterEachSuiteHook = false;
+      let executedBeforeAllCaseHook = false;
+      let executedAfterAllCaseHook = false;
+
```
Comment (saragee3) [inline src/test_case.ts:39]: catching up... why all these flags? and why did it need to be fast-tracked (1 approval)?

Comment (crookse) [reply src/test_case.ts:39]: it's because of the way deno test works. deno test queues up the test cases before running them and since we're bound to deno test, we need to put the hooks in the test cases. if we don't, then all of the hooks will run before any tests. since the hooks are in the test case, the only way i could see the hooks working properly is with these flags.

on the note about 1 approval. i've only ever required 1 approval. should we change to a 2 approval system?
