### PR TITLE
fix: Add autocompletion to `Rhum.asserts`

### LINKED ISSUE #63: Rhum.asserts has no autocompletion
## Description

When using the "shortcut" `Rhum.asserts` to build assertions we don't get intellisense support.

## To Reproduce

1. Import Rhum `v1.1.4`
2. Attempt to access auto completion for `Rhum.asserts`
3. Notice nothing relevant will show up
4. If you type the correct function name the assertion will still work as expected

## Expected behavior

I expected to get autocompletion support, the same we have for all Rhum 😅

## Suggested Solution(s)

I've been able to "export" functions with autocompletion by using a interface + a const that complied to that interface.

This is the snippet that worked for me. However those functions *are declared inside my module* so I'm not sure if this would work for mapping `Deno.test` calls.

```typescript
/**
 * Default functions for creating primitives with Dixture.
 */
export const dixtureFns: GenerationFunctions = {
  BigInt: createBigInt,
  Bool: createBoolean,
  Number: createNumber,
  String: createString,
  NamedString: <T>(prefix: keyof T) => createString(prefix.toString()),
  Int: () => createNumber(true),
  FutureDate: () => createDate(),
  PastDate: () => createDate(false),
};
```

The whole snippet can be found [here](https://github.com/rodolphocastro/dixture/blob/b53d2aa693044cdf22dbcf3f9ad10bb228f7d0cd/src/_factory.ts#L59)

The following test suites also replicate the error (as of version v1.1.4 at least): [dixture unit tests](https://github.com/rodolphocastro/dixture/tree/master/tests). _Note: I attempted to get that autocompletion to work on `deps.ts` and on the other files as well. No such luck_.

## Screenshots

The following show my attempts to get some suggestions for Rhum.asserts

rhum asserts
Code_1QnTwHE7Z3
Code_Tr1GabVEKy
Code_yKemxoFi3p

## Desktop

- OS: Windows 10 2004
- Version `v1.1.4`
- IDE: VsCode 1.49.1 w/ Deno.Land extension
- Deno Version: 1.4.0

### PR DESCRIPTION
**Pull request by ebebbington**
Fixes #63 

**Description**

* Issue was because when we did `asserts: {[key: string]: Function}`, it was just too dynamic and provided no intellisense

* With the help from #63, managed to create a type to assign to `asserts`

### CODE REVIEW

File: mod.ts [hunk 1]
```diff
@@ -64,7 +64,7 @@ export class RhumRunner {
    *     Rhum.asserts.assertEquals(true, false); // fail
    */
   // deno-lint-ignore ban-types Reason for this is, deno lint no longer allows `Function` and instead needs us to be explicit: `() => void`, but  because  we couldn't use that to  type the properties (we would just be copying Deno's interfaces word for word), we have to deal with `Function
-  public asserts: { [key: string]: Function } = asserts;
+  public asserts: { [key in assertions]: Function } = asserts;
```
Comment (Guergeiro) [inline mod.ts:67]: Problem with this is that we don't have function support when you autocomplete.
If you use `public asserts = asserts` we have that support, but it doesn't build because of a type problem

Comment (ebebbington) [reply mod.ts:67]: What do you mean by “autocomplete”? Like using Rhum.asserts. Or the asserts Parma’s?

Comment (Guergeiro) [reply mod.ts:67]: Essentially with this PR, we will have autocomplete in terms of the methods name that appears, but not their respective arguments.
- With `public asserts: { [key in assertions]: Function } = asserts;`, when typing `Rhum.asserts.*` it autocompletes to `Rhum.asserts.assertEquals`.
- With `public asserts = asserts`, when typing `Rhum.asserts.*` it autocompletes to `Rhum.asserts.assertEquals(first, second)` (don't actually know the param names here).

Comment (ebebbington) [reply mod.ts:67]: we could just do this then:
```
const asserts: {
  assertEquals: StdAsserts.assertEquals,
  ...
} = 
  ...
}
```
? and say a new one is developed by the deno team, if a user tries to use it (which they won't be able to), then can just make an issue - i think the main point is we would already have a tonne of assertion methods

Comment (Guergeiro) [reply mod.ts:67]: But do you understand the point I'm trying to make? Other than that, everything is okay by me. Actually, it already was before :D

Comment (ebebbington) [reply mod.ts:67]: Yeah i complete get you, essentially we have 2 problems:
* Add autocomplete to `Rhum.asserts` methods (this pr solved)
* Add autocomplete to the method parameters (this pr doesn't solve but you raised)

Whilst yeah, this PR only has a positive change, you did raise the point of the parameters which is **ideal** to have of course

What do you think about doing `const asserts: { the asserts } = { ... }`, so we can have autocomplete for methods **and** parameters?

Comment (Guergeiro) [reply mod.ts:67]: I tried playing with that a bit, but I wasn't able to make the tests pass. Can you try (using this branch as well) and I check out if it works as well on mine (I'm using VIM, but with a compatibility layer that uses VSCode extension to give autocomplete).

Comment (ebebbington) [reply mod.ts:67]: Yeah i'll give it try 👍

Comment (ebebbington) [reply mod.ts:67]: Unable to get it working... i think for now the autocompletion of methods is just a bonus, and i'll make an issue to track adding intellisense for the param stuff?

**Review by Guergeiro — APPROVED** [review]
